import { Blogger } from '../_models/blogger';

export const bloggersInit: Blogger[] = [
   {
      id: 0,
      name: 'Coleman Acevedo',
      website: 'colemanacevedo.io',
      picture_url: 'https://randomuser.me/api/portraits/women/19.jpg',
      email: 'contact@colemanacevedo.io',
      friends: [1, 2],
   },

   {
      id: 4,
      name: 'Bullock Phelps',
      website: 'bullockphelps.io',
      picture_url: 'https://randomuser.me/api/portraits/women/65.jpg',
      email: 'contact@bullockphelps.io',
      friends: [5],
   },
   {
      id: 7,
      name: 'Fern Mckee',
      website: 'fernmckee.io',
      picture_url: 'https://randomuser.me/api/portraits/women/82.jpg',
      email: 'contact@fernmckee.io',
      friends: [4, 6],
   },
   {
      id: 8,
      name: 'Addie Greene',
      website: 'addiegreene.io',
      picture_url: 'https://randomuser.me/api/portraits/women/91.jpg',
      email: 'contact@addiegreene.io',
      friends: [7, 9, 10],
   },
   {
      id: 13,
      name: 'Sandy Mcconnell',
      website: 'sandymcconnell.io',
      picture_url: 'https://randomuser.me/api/portraits/men/38.jpg',
      email: 'contact@sandymcconnell.io',
      friends: [11, 12, 0],
   },
   {
      id: 14,
      name: 'Estelle Stevenson',
      website: 'estellestevenson.io',
      picture_url: 'https://randomuser.me/api/portraits/men/48.jpg',
      email: 'contact@estellestevenson.io',
      friends: [15, 16, 17],
   },
   {
      id: 9,
      name: 'Gena Owens',
      website: 'genaowens.io',
      picture_url: 'https://randomuser.me/api/portraits/women/2.jpg',
      email: 'contact@genaowens.io',
      friends: [18, 19, 2],
   },
   {
      id: 10,
      name: 'Martin Mcmillan',
      website: 'martinmcmillan.io',
      picture_url: 'https://randomuser.me/api/portraits/men/5.jpg',
      email: 'contact@martinmcmillan.io',
      friends: [],
   },
   {
      id: 11,
      name: 'Franks Cleveland',
      website: 'frankscleveland.io',
      picture_url: 'https://randomuser.me/api/portraits/men/61.jpg',
      email: 'contact@frankscleveland.io',
      friends: [9, 4, 12],
   },
   {
      id: 12,
      name: 'Louise Hopper',
      website: 'louisehopper.io',
      picture_url: 'https://randomuser.me/api/portraits/men/2.jpg',
      email: 'contact@louisehopper.io',
      friends: [0, 3, 11],
   },
   {
      id: 15,
      name: 'Jacklyn Boyd',
      website: 'jacklynboyd.io',
      picture_url: 'https://randomuser.me/api/portraits/men/24.jpg',
      email: 'contact@jacklynboyd.io',
      friends: [2],
   },
   {
      id: 5,
      name: 'Sharlene Frost',
      website: 'sharlenefrost.io',
      picture_url: 'https://randomuser.me/api/portraits/women/3.jpg',
      email: 'contact@sharlenefrost.io',
      friends: [],
   },
   {
      id: 6,
      name: 'Leonard Morrison',
      website: 'leonardmorrison.io',
      picture_url: 'https://randomuser.me/api/portraits/women/13.jpg',
      email: 'contact@leonardmorrison.io',
      friends: [9],
   },
   {
      id: 16,
      name: 'Hahn Mcgowan',
      website: 'hahnmcgowan.io',
      picture_url: 'https://randomuser.me/api/portraits/men/67.jpg',
      email: 'contact@hahnmcgowan.io',
      friends: [15, 11],
   },
   {
      id: 17,
      name: 'Lucy Mosley',
      website: 'lucymosley.io',
      picture_url: 'https://randomuser.me/api/portraits/men/34.jpg',
      email: 'contact@lucymosley.io',
      friends: [2],
   },
   {
      id: 18,
      name: 'Kramer Church',
      website: 'kramerchurch.io',
      picture_url: 'https://randomuser.me/api/portraits/men/30.jpg',
      email: 'contact@kramerchurch.io',
      friends: [],
   },
   {
      id: 1,
      name: 'Elliott Holden',
      website: 'elliottholden.io',
      picture_url: 'https://randomuser.me/api/portraits/women/68.jpg',
      email: 'contact@elliottholden.io',
      friends: [],
   },
   {
      id: 2,
      name: 'Massey Duncan',
      website: 'masseyduncan.io',
      picture_url: 'https://randomuser.me/api/portraits/women/1.jpg',
      email: 'contact@masseyduncan.io',
      friends: [17],
   },
   {
      id: 3,
      name: 'King Rosales',
      website: 'kingrosales.io',
      picture_url: 'https://randomuser.me/api/portraits/women/57.jpg',
      email: 'contact@kingrosales.io',
      friends: [15],
   },
   {
      id: 19,
      name: 'Salas Velazquez',
      website: 'salasvelazquez.io',
      picture_url: 'https://randomuser.me/api/portraits/men/75.jpg',
      email: 'contact@salasvelazquez.io',
      friends: [0, 3, 9],
   },
];
